---
title: "分子遺伝学"
author: "Ryo Yamada"
date: "2017年6月13日"
output: 
  html_document:
    toc: true
    toc_depth: 6
    number_section: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 分子遺伝学とは〜６コマの概観

全６回
６ｘ９０＝５４０分

１ユニット１５分ｘ６＝９０分

６ｘ６＝３６ユニット

## 遺伝学

### 遺伝学とは
https://en.wikipedia.org/wiki/Genetics
```{}
Genetics is the study of genes, genetic variation, and heredity in living organisms. It is generally considered a field of biology, but intersects frequently with many other life sciences and is strongly linked with the study of information systems.
```
### 遺伝子とは
### 遺伝するとは
### 情報とは

http://www7a.biglobe.ne.jp/~number/entropy.html 
http://www.geneticentropy.org/whats-genetic-entropy 
http://www.morganclaypool.com/doi/abs/10.2200/S00151ED1V01Y200809BME023 
### ジェノタイプとフェノタイプ


## 遺伝学と確率・統計学

### 遺伝学と統計学の歴史

### 確率事象
#### 離散的確率事象
#### 連続的確率事象

### 確率事象と確率分布

## 分子遺伝学の基礎

### DNA,RNA,たんぱく質

#### コドン

#### 遺伝子機能〜質と量、産生と分解〜

### オミクス
ゲノム
エピゲノム
トランスクリプトーム
プロテオーム
メタボローム
フェノーム
#### 個別と全体

#### オミクス間の関係



# 生命の起源と歴史

## 生命とは

### 生命の必須要素

### RNAワールド仮説


## 進化

### 進化、変化、淘汰、適応
### 表現型の進化
### 遺伝子型の進化

## 変異
### 中立的変異
### 致死的変異
### 有利な変異・不利な変異
### 多様性と有利・不利

## 進化と種分化
### 種とは
### 種分化
### 系統樹
### 遺伝的多様性
#### 種間の遺伝的多様性
#### 種内の遺伝的多様性
#### 個体内細胞間の遺伝的多様性

# 分子系統学
## 系統樹

## 分子時計

## DNA配列の違いと距離
遺伝子配列の距離

## アラインメント

## 遠近関係

## 距離と距離行列

## 木を作る

## 階層的クラスタリング

## 配列の保存性

## オーソログ、シンテニー


# 遺伝的多様性

## 種間の遺伝的多様性
## 種内の遺伝的多様性
## 個体内細胞間の遺伝的多様性

# 遺伝子多型
種内遺伝的多様性

## 遺伝子多型の種類と分類
多型の分類

集団のアレル頻度

個体内のヘテロ箇所数
## アレルとジェノタイプ

## 遺伝子多型の出来方

### 突然変異
### 遺伝的浮動
#### 拡散方程式
### 交叉・組換え



## HWE

### 集団構造化とHWD

## 遺伝的多様性と人類の歴史

### Out of Africa
### 乳糖分解酵素

# 疾患の分子遺伝学

## メンデル型遺伝性疾患

## 家系図の描き方

### 常染色体性

### 性染色体性

### ミトコンドリア性

### 優性と劣性

### 優性と劣性の分子機構

### 確率と尤度
確率計算
尤度計算

## 複合遺伝性疾患
### 相加モデル
### 発病リスクと閾値モデル
### 多因子遺伝と正規分布

## 体細胞変異
個体内細胞間遺伝的多様性
## 細胞のジェノタイプ、細胞のフェノタイプ
### 分化とエピゲノム

## 生殖細胞系列と体細胞系列

## 体細胞系列変異と癌

## 体細胞モザイク

# まとめ
簡易試験






